### PR TITLE
Integrate with GH Actions, codecov.io and improve coverage by adding tests and removing unused code

### PR DESCRIPTION
**Pull request by fortizpenaloza**
- Refactor exception handling blocks by adding a collaborator to make it more portable
- Refactor dynamic arrays to make it more portable
- Add integration with GitHub Actions
- Add integration with codecov.io 
- Add tests and delete unused code to improve coverage
- Add installation docs

### CODE REVIEW

**Comment by fortizpenaloza** [comment]
@svenvc If you're ok with the requested changes I'll perform a few more, I've to change mostly links (badges and installation instructions). Should I do it in this PR, or do I open a new one following the merge?

For the codecov integration, you need to register a secret on `Settings` > `Secrets`. Sign up and log in to  https://about.codecov.io first, it's very simple.

**Comment by svenvc** [comment]
Hi Francisco,

This looks all OK to me (your removed a couple of setters that were probably unused), so I am just going to merge this to see where this leads us.

I tried to activate CodeCov and did add an Action secret, I hope I did it right.

Sven

**Comment by svenvc** [comment]
And of course, thank you for your efforts !

**Comment by svenvc** [comment]
Some of the links that you committed still refer to your branch, but you already said so.

**Comment by fortizpenaloza** [comment]
> Some of the links that you committed still refer to your branch, but you already said so.

Yes, I'll fix that right away. I need to use mine to see the results.

**Comment by fortizpenaloza** [comment]
> Hi Francisco,
> 
> This looks all OK to me (your removed a couple of setters that were probably unused), so I am just going to merge this to see where this leads us.
> 
> I tried to activate CodeCov and did add an Action secret, I hope I did it right.
> 
> Sven

[Here](https://app.codecov.io/gh/svenvc/memcached/) you could find the info on how set it up.

See step "Update coverage to Codecov" on https://github.com/svenvc/memcached/runs/2116068576 . There's an issue `Invalid request parameters`. I'll investigate that.

**Pull request merged**
